name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'               # Build when you push a tag like v1.0.0
  workflow_dispatch:        # Also allow manual runs from the Actions tab

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      # If you ever see missing-module errors at runtime,
      # add --hidden-import MODULE (e.g. --hidden-import openpyxl)
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name ExcelMergeGUI ExcelMergeGUI.py

      # Artifact = shows up on the workflow run page
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExcelMergeGUI
          path: dist/ExcelMergeGUI.exe

      # If this run was triggered by a tag (v1.0.0 etc.), attach the EXE to a Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/ExcelMergeGUI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
