name: Build Windows EXE

on:
  push:
    tags: ['v*']           # builds when you push a tag like v1.0.0
  workflow_dispatch:        # allows manual runs

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      # Auto-find ExcelMergeGUI.py anywhere (works even if it's in "Merge the Tab")
      - name: Locate script automatically
        shell: pwsh
        run: |
          $file = Get-ChildItem -Recurse -File | Where-Object { $_.Name -ieq 'ExcelMergeGUI.py' } | Select-Object -First 1
          if (-not $file) {
            Write-Host "Could not find ExcelMergeGUI.py. Listing .py files:"
            Get-ChildItem -Recurse -File -Include *.py | ForEach-Object { $_.FullName }
            throw "ExcelMergeGUI.py not found"
          }
          "SCRIPT_PATH=$($file.FullName)" | Out-File $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "Found script at: $($file.FullName)"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --onefile --noconsole --hidden-import openpyxl --name ExcelMergeGUI "$env:SCRIPT_PATH"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExcelMergeGUI
          path: dist/ExcelMergeGUI.exe

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ExcelMergeGUI.exe
