name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'          # builds when you push a tag like v1.0.0
  workflow_dispatch:   # lets you run it manually

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      # Auto-find your script (ExcelMerge.py or ExcelMergeGUI.py) anywhere in the repo
      - name: Locate script
        shell: pwsh
        run: |
          $file = Get-ChildItem -Recurse -File -Include ExcelMerge*.py | Select-Object -First 1
          if (-not $file) {
            Write-Host "No Exc

        uses: softprops/action-gh-release@v2
        with:
          files: dist/ExcelMergeGUI.exe
